import {strict as assert} from 'node:assert';
import {filterProcedures,changedFields,displayValue,categoryForTitle} from '../src/procedure-view.js';
const items=[{title:'Créditos — Resolución',questions:'préstamo canal',support:'SCA',published:true},{title:'Cobranzas',questions:'efectivo',support:'AS400',published:false}];
assert.equal(filterProcedures(items,'CREDITOS resolucion').length,1);
assert.equal(filterProcedures(items,'prestamo SCA').length,1);
assert.equal(filterProcedures(items,'efectivo')[0].published,false);
assert.equal(filterProcedures(items,'inexistente').length,0);
assert.equal(filterProcedures(items,'   ').length,2);
assert.deepEqual(changedFields({steps:'Antes',published:false},{steps:'Después',published:true}).map(x=>x.key),['steps','published']);
assert.equal(displayValue('published',false),'Borrador');
assert.deepEqual(changedFields({title:'Igual',updatedAt:1},{title:'Igual',updatedAt:2}),[]);
assert.equal(categoryForTitle('1.4 Sistema FOGAPY — Alta de usuarios'),'Sistema FOGAPY');
assert.equal(categoryForTitle('2.2 Desembolso — Control de retorno EE'),'Desembolsos');
assert.equal(categoryForTitle('5 Equifax — Contacto'),'Equifax');
assert.equal(categoryForTitle('Cambio de auca clientes'),'Administración de clientes');
assert.equal(categoryForTitle('Tema sin clasificar'),'Otros procedimientos');
console.log('13 pruebas de búsqueda, comparación y categorías correctas.');
