const {test}=require('node:test'),assert=require('node:assert/strict'),D=require('../../stockpro-firebase/functions/domain');
const ctx={day:'2026-10-04'},person={name:'Cliente',doc:'',phone:'',address:'',limit:999999,category:'EXCELENTE'};
const actor=role=>({uid:role,role,moduleRoles:{clientes:['ADMIN','CAJERO','ENCARGADO']}});
test('new clients always start Nuevo at 300000 for every role; legacy values preserved',()=>{for(const role of D.ROLES.filter(r=>r!=='DUENO')){let s=D.apply(D.empty(),'saveClient',person,actor(role),ctx);assert.equal(s.clients[0].limit,300000);assert.equal(s.clients[0].category,'NUEVO');s.clients[0].limit=450000;delete s.clients[0].category;s=D.apply(s,'saveClient',{...person,id:s.clients[0].id},actor('CAJERO'),ctx);assert.equal(s.clients[0].limit,450000);assert.equal(s.clients[0].category,undefined)}});
test('only Encargado edits classification and limit; class caps enforced',()=>{let s=D.apply(D.empty(),'saveClient',person,actor('CAJERO'),ctx);const id=s.clients[0].id;for(const role of ['ADMIN','CAJERO']){const q=D.apply(s,'saveClient',{...person,id,category:'MALO',limit:0},actor(role),ctx);assert.equal(q.clients[0].limit,300000);assert.equal(q.clients[0].category,'NUEVO')}for(const [category,limit] of Object.entries(D.CREDIT_LIMITS)){const q=D.apply(s,'saveClient',{...person,id,category,limit},actor('ENCARGADO'),ctx);assert.equal(q.clients[0].limit,limit);assert.equal(q.clients[0].category,category);assert.throws(()=>D.apply(s,'saveClient',{...person,id,category,limit:limit+1},actor('ENCARGADO'),ctx))}});
test('last weekday handles leap years, weekends and December rollover',()=>{for(const [day,due] of [['2026-10-04','2026-10-30'],['2026-05-01','2026-05-29'],['2028-02-01','2028-02-29'],['2026-01-31','2026-02-27'],['2023-12-31','2024-01-31']])assert.equal(D.defaultCreditDue(day),due)});
test('only manager can reschedule unpaid credit; balance and original date stay intact',()=>{const s=D.empty();s.credits=[{id:1,date:'2026-10-01',dueDate:'2026-10-30',balance:100,amount:100}];for(const role of ['ADMIN','CAJERO'])assert.throws(()=>D.apply(s,'setCreditDueDate',{id:1,dueDate:'2026-11-02'},actor(role),ctx),e=>e.code==='permission-denied');const next=D.apply(s,'setCreditDueDate',{id:1,dueDate:'2026-11-02'},actor('ENCARGADO'),ctx);assert.equal(next.credits[0].balance,100);assert.equal(next.credits[0].dueDate,'2026-11-02');assert.throws(()=>D.apply(s,'setCreditDueDate',{id:1,dueDate:'2026-02-31'},actor('ENCARGADO'),ctx));s.credits[0].balance=0;assert.throws(()=>D.apply(s,'setCreditDueDate',{id:1,dueDate:'2026-11-02'},actor('ENCARGADO'),ctx))});

function arrearsSaleState(){const s=D.empty();s.cash={...s.cash,isOpen:true,sessionId:'test'};s.clients=[{id:1,name:'Ana',limit:300000}];s.products=[{id:1,name:'Arroz',stock:10,price:100,vat:10}];s.credits=[{id:1,clientId:1,balance:50,dueDate:'2026-10-03'}];return s;}
const salePayload={clientId:1,items:[{productId:1,qty:1,price:100,vat:10}]};
test('arrears blocks all payment methods without changing stock, sales or debt',()=>{for(const pay of ['Efectivo','Transferencia','Tarjeta de débito','Tarjeta de crédito','Crédito']){const s=arrearsSaleState(),original=structuredClone(s);assert.throws(()=>D.apply(s,'finishSale',{...salePayload,pay},actor('CAJERO'),ctx),/Cliente en mora/);assert.deepEqual(s,original);}});
test('due today, settled debt and another client debt do not block sales',()=>{for(const change of [c=>c.dueDate='2026-10-04',c=>c.balance=0,c=>c.clientId=2]){const s=arrearsSaleState();change(s.credits[0]);const next=D.apply(s,'finishSale',{...salePayload,pay:'Efectivo'},actor('CAJERO'),ctx);assert.equal(next.sales.length,1);assert.equal(next.products[0].stock,9);}});
