const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.resolve(__dirname,'../../docs/stockpro/dashboard-client.js'),'utf8');
const ctx={};vm.createContext(ctx);vm.runInContext(source.slice(0,source.indexOf('const dashboardColors')),ctx);
test('daily charts group amounts, isolate days and preserve unknown categories',()=>{
 const data={products:[{id:1,category:'Alimentos'},{id:2,category:'Bebidas'}],sales:[{date:'2026-10-03',pay:'Efectivo',total:50,items:[{productId:1,qty:2,price:10},{productId:2,qty:3,price:10}]},{date:'2026-10-03',pay:'Crédito',total:15,items:[{productId:99,qty:1,price:15}]},{date:'2026-10-02',pay:'Efectivo',total:999,items:[]}]};
 const r=JSON.parse(JSON.stringify(ctx.dailySalesBreakdown(data,'2026-10-03')));
 assert.deepEqual(r.payments,[{label:'Efectivo',value:50},{label:'Crédito',value:15}]);assert.deepEqual(r.categories,[{label:'Bebidas',value:30},{label:'Alimentos',value:20},{label:'Sin categoría',value:15}]);
 assert.deepEqual(JSON.parse(JSON.stringify(ctx.dailySalesBreakdown(data,'2026-10-04'))),{payments:[],categories:[]});
});
function liveSetup(){let timer,callback,unsubscribed=false,calls=0;const c={authGeneration:1,auth:{currentUser:{uid:'a'}},roleBlocked:false,conflict:false,navigator:{onLine:true},envelope:{revision:1,pending:false},syncing:false,reading:false,cart:[],document:{querySelector:()=>null},syncState:'connected',setTimeout:fn=>{timer=fn;return 1},clearTimeout:()=>{timer=null},retrySync:async()=>{calls++;c.envelope.revision=2;c.envelope.pending=false},cloudFailure:e=>{throw e},sparkRoot:()=>({collection:()=>({doc:()=>({onSnapshot:(options,fn)=>{callback=fn;return()=>unsubscribed=true}})})})};vm.createContext(c);vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../docs/stockpro/live-client.js'),'utf8'),c);c.startLiveUpdates(1);return {c,event:r=>callback({exists:true,data:()=>({revision:r}),metadata:{}}),tick:async()=>{const fn=timer;timer=null;if(fn)await fn()},calls:()=>calls,stopped:()=>unsubscribed};}
test('remote revision refreshes once, catches changes during reading, avoids idle polling',async()=>{const t=liveSetup();t.event(2);t.c.reading=true;await t.tick();assert.equal(t.calls(),0);t.c.reading=false;await t.tick();assert.equal(t.calls(),1);t.event(2);await t.tick();assert.equal(t.calls(),1);t.c.stopLiveUpdates();assert(t.stopped())});
test('live update defers active forms and ignores previous sessions',async()=>{const t=liveSetup();t.c.cart=[{}];t.event(2);await t.tick();assert.equal(t.calls(),0);t.c.cart=[];t.c.authGeneration=2;await t.tick();assert.equal(t.calls(),0)});
