const {test,before,after}=require('node:test'),fs=require('node:fs'),path=require('node:path'),{initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,getDoc,setDoc,writeBatch,serverTimestamp}=require('firebase/firestore'),D=require('../../stockpro-firebase/functions/domain');let env,serial=0;
const base={id:1,date:'2026-10-01',supplierId:1,supplier:'Proveedor',productId:1,product:'Arroz',qty:5,cost:100,total:500,invoice:'A',operatorUid:'creator'},product={id:1,sku:'1',name:'Arroz',category:'Alimentos',price:200,stock:10,min:1,avg:1,vat:10};
const dbFor=uid=>env.authenticatedContext(uid,{email:uid+'@purchase.test',email_verified:true}).firestore();
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-purchase-review',firestore:{host:'127.0.0.1',port:8088,rules:fs.readFileSync(path.resolve(__dirname,'../firestore.rules'),'utf8')}});await env.clearFirestore();await env.withSecurityRulesDisabled(async ctx=>{const db=ctx.firestore();for(const [uid,role] of [['admin','ADMIN'],['manager','ENCARGADO'],['cashier','CAJERO'],['owner','DUENO']])await setDoc(doc(db,'stockproAccess/'+uid+'@purchase.test'),{email:uid+'@purchase.test',name:uid,role,active:true,...(role==='DUENO'?{storeIds:['despensa']}:{storeId:'despensa'})});await setDoc(doc(db,'stockproConfig/main'),{ownerEmail:'admin@purchase.test'});await setDoc(doc(db,'stockproDespensas/despensa'),{name:'Demo',active:true});await setDoc(doc(db,'stockproStores/despensa/suppliers/1'),{id:1,name:'Proveedor'});await setDoc(doc(db,'stockproStores/despensa/products/1'),product);await setDoc(doc(db,'stockproStores/despensa/products/2'),{...product,id:2,sku:'2',name:'Fideos',stock:2});await setDoc(doc(db,'stockproStores/despensa/purchases/1'),base);});});after(()=>env?.cleanup());
async function change({uid='manager',action='editPurchase',patch={qty:3,total:300},tamper=()=>{},stock=true,remove=false}={}){const db=dbFor(uid),root='stockproStores/despensa/',old=(await getDoc(doc(dbFor('admin'),root+'purchases/1'))).data(),m=(await getDoc(doc(dbFor('admin'),root+'meta/state'))).data(),opid='purchase-'+(++serial),next={...old,...patch},entry={action,actorUid:uid,actorEmail:uid+'@purchase.test',at:Date.now(),reason:'Corrección recepción',before:D.purchaseValues(old),after:D.purchaseValues(next)};next.history={...old.history,[opid]:entry};next.lastChange=opid;next._op=opid;const batch=writeBatch(db),context={role:{admin:'ADMIN',manager:'ENCARGADO',cashier:'CAJERO',owner:'DUENO'}[uid],cashMoveId:'',closingId:'',action,opid,actorUid:uid,saleId:0,creditId:0,paymentId:'',purchaseId:1,updatedAt:serverTimestamp(),revision:(m?.revision||0)+1};if(stock&&action==='editPurchase')for(const id of new Set([old.productId,next.productId])){const ref=doc(db,root+'products/'+id),p=(await getDoc(ref)).data();batch.set(ref,{...p,stock:p.stock+(next.productId===id?next.qty:0)-(old.productId===id?old.qty:0),_op:opid});}tamper(next,entry,context);if(remove)batch.delete(doc(db,root+'purchases/1'));else batch.set(doc(db,root+'purchases/1'),next);batch.set(doc(db,root+'meta/state'),{...context,schema:9});batch.set(doc(db,root+'operations/'+uid+'_'+opid),context);return batch.commit();}
test('only manager; missing/forged audit, stock omission and changes to creator denied',async()=>{for(const uid of ['admin','cashier','owner'])await assertFails(change({uid}));await assertFails(change({stock:false}));for(const tamper of [(p)=>delete p.history,(p,a)=>a.actorUid='admin',(p,a)=>a.actorEmail='other@example.test',(p,a)=>a.at=0,(p,a)=>a.before.total=999,(p,a)=>a.after.total=999,(p)=>p.operatorUid='manager',(p)=>p.extra=1,(p,a)=>a.reason=''])await assertFails(change({tamper}));});
test('manager correction succeeds, audit append and stock coupled',async()=>{await assertSucceeds(change());await assertFails(change({patch:{qty:4,total:400},tamper:p=>{const key=Object.keys(p.history)[0];p.history[key].reason='rewritten';}}));await assertSucceeds(change({patch:{qty:4,total:400}}));});
test('changing product requires stock adjustment on both products',async()=>{await assertFails(change({patch:{productId:2,product:'Fideos',qty:2,total:200},stock:false}));await assertSucceeds(change({patch:{productId:2,product:'Fideos',qty:2,total:200}}));});
test('verification cannot also change fields; verified purchase locked including admin restore/delete',async()=>{await assertFails(change({action:'verifyPurchase',patch:{verified:true,invoice:'changed'}}));await assertSucceeds(change({action:'verifyPurchase',patch:{verified:true}}));await assertFails(change({patch:{qty:6,total:600}}));await assertFails(change({action:'verifyPurchase',patch:{verified:true}}));await assertFails(change({uid:'admin',action:'restore',patch:{invoice:'bypass'}}));await assertFails(change({uid:'admin',action:'restore',remove:true}));});
