const {test}=require('node:test');const assert=require('node:assert/strict');const D=require('../functions/domain');
const admin={uid:'admin',role:'ADMIN',active:true},cashier={uid:'cashier',role:'CAJERO',active:true},manager={uid:'manager',role:'ENCARGADO',active:true};
const ctx={opid:'operation-test',now:'2026-10-01T15:00:00Z',day:'2026-10-01'};
function seed(){const s=D.empty();s.products=[{id:1,name:'Arroz',sku:'A',category:'Almacén',price:11000,cost:7000,vat:10,stock:10,min:2,avg:1}];s.clients=[{id:1,name:'Cliente',doc:'1',phone:'',address:'',limit:30000}];s.suppliers=[{id:1,name:'Proveedor',ruc:'1',phone:'',contact:''}];s.stamps=[{id:1,number:'123',establishment:'001',point:'001',validFrom:'2026-01-01',validTo:'2026-12-31',start:1,end:100,next:1,enabled:true,note:''}];return s}
const sale={items:[{productId:1,price:11000,vat:10,qty:2}],clientId:1,pay:'Efectivo',invoice:{stampId:1,doc:'1',name:'Cliente'}};
test('cashier cannot adjust stock, manage suppliers, stamps or limits',()=>{for(const action of ['saveProduct','saveStockMove','saveSupplier','savePurchase','saveStamp','saveCredit','restore'])assert.throws(()=>D.apply(seed(),action,{},cashier,ctx),e=>e.code==='permission-denied')});
test('manager has stock permissions, not sales or cash',()=>{for(const action of ['finishSale','openCash','saveCreditPayment','saveClient'])assert.throws(()=>D.apply(seed(),action,{},manager,ctx));const s=D.apply(seed(),'saveStockMove',{id:1,type:'ENTRADA',qty:2,detail:'Recepción'},manager,ctx);assert.equal(s.products[0].stock,12)});
test('manager cannot create admins, edit admins, self-promote or disable initial superuser',()=>{assert.throws(()=>D.manageAllowed(manager,null,'ADMIN','other','admin'));assert.throws(()=>D.manageAllowed(manager,admin,'CAJERO','admin2','admin'));assert.throws(()=>D.manageAllowed(manager,manager,'CAJERO','manager','admin'));assert.throws(()=>D.manageAllowed(admin,admin,'CAJERO','admin','admin'));D.manageAllowed(manager,cashier,'ENCARGADO','cashier','admin')});
test('sale derives prices, taxes, stock and invoice on server',()=>{let s=D.apply(seed(),'openCash',{amount:100000},cashier,ctx);s=D.apply(s,'finishSale',sale,cashier,ctx);assert.equal(s.sales[0].total,22000);assert.equal(s.sales[0].taxes.iva10,2000);assert.equal(s.products[0].stock,8);assert.equal(s.stamps[0].next,2);assert.equal(s.sales[0].invoice.number,'001-001-0000001');assert.equal(s.sales[0].operatorUid,'cashier');assert.equal(D.expected(s,'cashier'),122000)});
test('forged prices and duplicate product lines rejected',()=>{const s=D.apply(seed(),'openCash',{amount:0},cashier,ctx);assert.throws(()=>D.apply(s,'finishSale',{...sale,items:[{...sale.items[0],price:1}]},cashier,ctx));assert.throws(()=>D.apply(s,'finishSale',{...sale,items:[...sale.items,...sale.items]},cashier,ctx))});
test('credit sale respects authorized limit; payment updates only own till',()=>{let s=D.apply(seed(),'openCash',{amount:0},cashier,ctx);s=D.apply(s,'finishSale',{...sale,pay:'Crédito',dueDate:'2026-10-10'},cashier,ctx);assert.equal(s.credits[0].balance,22000);assert.throws(()=>D.apply(s,'finishSale',{...sale,pay:'Crédito',dueDate:'2026-10-10'},cashier,ctx));s=D.apply(s,'saveCreditPayment',{id:1,date:'2026-10-01',amount:5000,method:'Efectivo',detail:''},cashier,ctx);assert.equal(s.credits[0].balance,17000);assert.equal(D.expected(s,'cashier'),5000)});
test('cashier cannot change a client credit limit',()=>{const s=D.apply(seed(),'saveClient',{id:1,name:'Cliente',doc:'1',phone:'1',address:'',limit:999999},cashier,ctx);assert.equal(s.clients[0].limit,30000)});
test('projections do not expose restricted collections or costs',()=>{const s=seed();s.sales=[{id:1,operatorUid:'admin'},{id:2,operatorUid:'cashier'}];s.credits=[{id:1}];const c=D.project(s,cashier);assert.equal(c.products[0].cost,0);assert.equal(c.suppliers.length,0);assert.equal(c.sales.length,1);const m=D.project(s,manager);assert.equal(m.clients.length,0);assert.equal(m.credits.length,0);assert.equal(m.stamps.length,0)});
test('negative amount, NaN and overpayment fail',()=>{assert.throws(()=>D.apply(seed(),'openCash',{amount:-1},cashier,ctx));assert.throws(()=>D.apply(seed(),'openCash',{amount:NaN},cashier,ctx))});

test('restore rejects corrupt values and preserves issued sales',()=>{let d=seed();d.products[0].stock=-1;assert.throws(()=>D.apply(seed(),'restore',{data:d},admin,ctx));d=seed();d.stamps[0].next=0;assert.throws(()=>D.apply(seed(),'restore',{data:d},admin,ctx));let s=D.apply(seed(),'openCash',{amount:0},admin,ctx);s=D.apply(s,'finishSale',sale,admin,ctx);assert.throws(()=>D.apply(s,'restore',{data:seed()},admin,ctx))});
test('calendar dates cannot roll into the next month',()=>{assert.throws(()=>D.apply(seed(),'savePurchase',{supplierId:1,productId:1,qty:1,cost:1,date:'2026-02-31',invoice:''},manager,ctx))});
test('supplier requires products from its category and protects linked catalog entries',()=>{let s=seed();const p={id:0,name:'Proveedor relacionado',ruc:'',phone:'',contact:'',category:'Almacén',productIds:[1]};assert.throws(()=>D.apply(s,'saveSupplier',{...p,productIds:[]},manager,ctx));assert.throws(()=>D.apply(s,'saveSupplier',{...p,category:'Otra'},manager,ctx));s=D.apply(s,'saveSupplier',p,manager,ctx);assert.deepEqual(s.suppliers.at(-1).productIds,[1]);assert.throws(()=>D.apply(s,'deleteProduct',{id:1},manager,ctx));assert.throws(()=>D.apply(s,'saveProduct',{...s.products[0],category:'Otra'},manager,ctx));});
