// Tests the actual callable handler with in-memory Firestore/Storage adapters.
// Complements emulator rules tests; does not simulate distributed transactions.
const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function harness(){
 const docs=new Map(),files=new Map();let seq=0;
 const snap=p=>({exists:docs.has(p),data:()=>docs.get(p),ref:ref(p),id:p.split('/').pop()});
 const ref=p=>({path:p,collection:c=>col(p+'/'+c),get:async()=>snap(p),delete:async()=>docs.delete(p),update:async v=>docs.set(p,{...docs.get(p),...v})});
 const col=p=>({doc:(i='event'+(++seq))=>ref(p+'/'+i),get:async()=>({docs:[...docs.keys()].filter(k=>k.startsWith(p+'/')&&!k.slice(p.length+1).includes('/')).map(snap)})});
 const db={doc:ref,collection:col,runTransaction:async fn=>{const writes=[];let wrote=false;const tx={get:async r=>{assert.equal(wrote,false,'reads must precede writes');return snap(r.path);},create:(r,v)=>{wrote=true;assert(!docs.has(r.path));writes.push(()=>docs.set(r.path,v));},update:(r,v)=>{wrote=true;assert(docs.has(r.path));writes.push(()=>docs.set(r.path,{...docs.get(r.path),...v}));},delete:r=>{wrote=true;writes.push(()=>docs.delete(r.path));}};const result=await fn(tx);writes.forEach(w=>w());return result;}};
 const bucket={deleteFiles:async({prefix})=>{for(const p of files.keys())if(p.startsWith(prefix))files.delete(p);},file:p=>({getMetadata:async()=>{if(!files.has(p))throw Error('missing');return [files.get(p)];},delete:async()=>files.delete(p)})};
 class HttpsError extends Error{constructor(code,msg){super(msg);this.code=code;}}
 const exports={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../functions/index.js'),'utf8'),{exports,require:n=>({'firebase-functions/v2/https':{onCall:(_,fn)=>fn,HttpsError},'firebase-admin/app':{initializeApp:()=>{}},'firebase-admin/firestore':{getFirestore:()=>db,Timestamp:{now:()=>({toDate:()=>new Date('2026-09-23T12:00:00Z')})}},'firebase-admin/storage':{getStorage:()=>({bucket:()=>bucket})},'node:crypto':require('node:crypto')})[n]});
 const call=(uid,data)=>exports.boardAction({auth:uid?{uid,token:{email:uid+'@example.com'}}:null,data});
 const profile=(uid,role='user',status='authorized')=>docs.set('users/'+uid,{ownerUid:uid,email:uid+'@example.com',role,status});
 const create=(uid='alice',iid='n1')=>call(uid,{action:'create',ownerUid:uid,id:iid,item:{type:'note',title:'Note',text:'content',x:0,y:0}});
 return {docs,files,call,profile,create};
}
test('unauthenticated access is rejected',async()=>{const h=harness();await assert.rejects(h.call(null,{action:'ensureProfile'}),{code:'unauthenticated'});});
test('self registration always creates pending ordinary user',async()=>{const h=harness();await h.call('alice',{action:'ensureProfile',role:'admin',status:'authorized'});assert.equal(h.docs.get('users/alice').role,'user');assert.equal(h.docs.get('users/alice').status,'pending');});
test('pending and blocked accounts cannot write',async()=>{for(const status of ['pending','blocked']){const h=harness();h.profile('alice','user',status);await assert.rejects(h.create(),{code:'permission-denied'});}});
test('owner cannot write another board or promote themselves',async()=>{const h=harness();h.profile('alice');await assert.rejects(h.call('alice',{action:'create',ownerUid:'bob',id:'n',item:{type:'note'}}),{code:'permission-denied'});await assert.rejects(h.call('alice',{action:'setStatus',uid:'alice',status:'authorized'}),{code:'permission-denied'});});
test('admin can authorize user; admin accounts are protected from panel changes',async()=>{const h=harness();h.profile('boss','admin');h.profile('alice','user','pending');await h.call('boss',{action:'setStatus',uid:'alice',status:'authorized'});assert.equal(h.docs.get('users/alice').status,'authorized');await assert.rejects(h.call('boss',{action:'setStatus',uid:'boss',status:'blocked'}));});
test('create discards injected owner and audit fields; duplicate IDs are idempotent',async()=>{const h=harness();h.profile('alice');await h.call('alice',{action:'create',ownerUid:'alice',id:'n1',item:{type:'note',ownerUid:'bob',createdBy:'boss',state:'purging'}});await h.create();assert.equal(h.docs.get('boards/alice/items/n1').ownerUid,'alice');assert.equal(h.docs.get('boards/alice/items/n1').createdBy,'alice');assert.equal(h.docs.get('boards/alice/items/n1').state,'active');});
test('edits require current revision and protect audit',async()=>{const h=harness();h.profile('alice');await h.create();await assert.rejects(h.call('alice',{action:'edit',ownerUid:'alice',id:'n1',revision:0,title:'new',text:'new',color:'note-blue'}),{code:'aborted'});await h.call('alice',{action:'edit',ownerUid:'alice',id:'n1',revision:1,title:'new',text:'new',color:'note-blue'});assert.equal(h.docs.get('boards/alice/items/n1').revision,2);});
test('soft delete retains data; only admin restores',async()=>{const h=harness();h.profile('alice');h.profile('boss','admin');await h.create();await h.call('alice',{action:'trash',ownerUid:'alice',id:'n1'});assert.equal(h.docs.get('boards/alice/items/n1').text,'content');await assert.rejects(h.call('alice',{action:'restore',ownerUid:'alice',id:'n1'}),{code:'permission-denied'});await h.call('boss',{action:'restore',ownerUid:'alice',id:'n1'});assert.equal(h.docs.get('boards/alice/items/n1').state,'active');});
test('purge requires admin and prior soft delete; audit survives purge',async()=>{const h=harness();h.profile('alice');h.profile('boss','admin');await h.create();await assert.rejects(h.call('boss',{action:'purge',ownerUid:'alice',id:'n1'}));await h.call('alice',{action:'trash',ownerUid:'alice',id:'n1'});await assert.rejects(h.call('alice',{action:'purge',ownerUid:'alice',id:'n1'}),{code:'permission-denied'});h.files.set('boards/alice/n1/file',{size:1});await h.call('boss',{action:'purge',ownerUid:'alice',id:'n1'});assert(!h.docs.has('boards/alice/items/n1'));assert.equal(h.files.size,0);assert([...h.docs.values()].some(d=>d.action==='purge-complete'));});
test('upload replacement keeps old attachment in recoverable trash',async()=>{const h=harness();h.profile('alice');h.profile('boss','admin');await h.create();async function upload(){const u=await h.call('alice',{action:'reserveUpload',ownerUid:'alice',id:'n1',name:'a.txt',type:'text/plain',size:3});h.files.set(u.path,{size:3,contentType:'text/plain'});await h.call('alice',{action:'attach',ownerUid:'alice',id:'n1',fileId:u.id});return u;}const first=await upload(),second=await upload();assert.equal(h.docs.get('boards/alice/items/n1/uploads/'+first.id).state,'trash');await h.call('boss',{action:'restoreUpload',ownerUid:'alice',id:'n1',fileId:first.id});assert.equal(h.docs.get('boards/alice/items/n1').attachment.id,first.id);assert.equal(h.docs.get('boards/alice/items/n1/uploads/'+second.id).state,'trash');});
test('active attachment cannot be purged independently',async()=>{const h=harness();h.profile('alice');h.profile('boss','admin');await h.create();const u=await h.call('alice',{action:'reserveUpload',ownerUid:'alice',id:'n1',name:'a',size:0});h.files.set(u.path,{size:0});await h.call('alice',{action:'attach',ownerUid:'alice',id:'n1',fileId:u.id});await assert.rejects(h.call('boss',{action:'purgeUpload',ownerUid:'alice',id:'n1',fileId:u.id}));});
test('file constraints, traversal and invalid positions are rejected',async()=>{const h=harness();h.profile('alice');await h.create();await assert.rejects(h.call('alice',{action:'move',ownerUid:'alice',id:'n1',x:-1,y:0}));await assert.rejects(h.call('alice',{action:'reserveUpload',ownerUid:'alice',id:'n1',name:'a',size:30*1024*1024}));await assert.rejects(h.call('alice',{action:'trash',ownerUid:'alice',id:'../bob'}));});
