import {auth,login,logout,watchAuth,isOwner,listProcedures,saveProcedure,errorMessage} from './firebase.js';
const $=id=>document.getElementById(id);let selected='',items=[];const fields=['title','questions','support','steps','hours','good','bad'];
function status(text){$('status').textContent=text}
function reset(){selected='';$('editor').reset();$('published').checked=false;$('edit-title').textContent='Nuevo procedimiento'}
function edit(item){selected=item.id;for(const key of fields)$(key).value=item[key]||'';$('published').checked=item.published;$('edit-title').textContent='Editar procedimiento';$('title').focus()}
async function refresh(){items=await listProcedures();$('list').replaceChildren();for(const item of items){const b=document.createElement('button');b.type='button';b.textContent=item.title+' · '+(item.published?'Publicado':'Borrador');b.onclick=()=>edit(item);$('list').append(b)}if(!items.length)$('list').textContent='Todavía no hay procedimientos.'}
$('login').onclick=async()=>{try{status('Abriendo Google para iniciar sesión…');await login()}catch(e){status(errorMessage(e))}};$('logout').onclick=()=>logout();$('new').onclick=reset;
$('editor').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{const data=Object.fromEntries(fields.map(k=>[k,$(k).value.trim()]));data.published=$('published').checked;await saveProcedure(selected,data);reset();await refresh();status('Procedimiento guardado en Firebase.')}catch(e){status(errorMessage(e))}finally{$('save').disabled=false}};
watchAuth(async user=>{$('logout').hidden=!user;$('login').hidden=!!user;$('workspace').hidden=true;if(!user){status('Ingresá con tu cuenta de administración.');return}if(!isOwner(user)){status('Esta cuenta no está autorizada para administrar los procedimientos.');return}status('Cargando procedimientos…');try{await refresh();$('workspace').hidden=false;status('Conectado a Firebase. Solo tu cuenta puede consultar y editar esta base.')}catch(e){status(errorMessage(e))}});
